#!/bin/bash

bb_server=my.rochester.edu

before=
expected=

transform()
{
	regex='/%TOKEN%/!d;s/.*%TOKEN% \("\(\([^"\]\|\\.\)*\)"\|\(\([^ \]\|\\.\)*\)\).*/\2\4/;'
	regex+='s/\\\([^\\]\)/\1/g;s/\\$//g;s/\\\\/\\/g'

	cred=`sed -n "/machine $bb_server/,/machine /p" <<< "$1"`
	user_id=`sed "${regex//%TOKEN%/login}" <<< $cred`
	password=`sed "${regex//%TOKEN%/password}" <<< $cred`

    echo "$password"
}

while read -r str; do
    if [[ -z "$before" ]]; then
        before="$str"
        continue
    fi
    expected="$str"

    transformed="$(transform "machine $bb_server password $before login name")"

    if [[ "$transformed" != "$expected" ]]; then
        echo "Password: '$before'; Expected; '$expected'; Got: '$transformed'"
    fi

    expected=
    before=
done <passwords

exit 0

