#!/bin/bash

before=
expected=

transform()
{
    sed -n \
        's/\("\(\([^"\]\|\\.\)*\)"\|\(\([^\]\|\\.\)*\)\)/\2\4/p' \
        <<< "$1" | sed 's/\\\([^\\]\)/\1/g;s/\\$//g;s/\\\\/\\/g'
}

while read -r str; do
    if [[ -z "$before" ]]; then
        before="$str"
        continue
    fi
    expected="$str"

    transformed="$(transform "$before")"

    if [[ "$transformed" != "$expected" ]]; then
        echo "Password: $before; Expected; $expected; Got: $transformed"
    fi

    expected=
    before=
done <passwords

exit 0

